lib/shrtener_web/router.ex
defmodule ShrtenerWeb.Router do
  use ShrtenerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ShrtenerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", UrlController, :new
    resources "/urls", UrlController, only: [:new, :create]
    get "/:shortcode", UrlController, :redirect_shortcode
  end

  # Other scopes may use custom stacks.
  # scope "/api", ShrtenerWeb do
  #   pipe_through :api
  # end
end

lib/shrtener/application.ex
defmodule Shrtener.Application do
  use Application

  alias Shrtener.Repo
  alias ShrtenerWeb.Endpoint

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Repo, []),
      # Start the endpoint when the application starts
      supervisor(Endpoint, []),
      # Start your own worker by calling: Shrtener.Worker.start_link(arg1)
      # worker(Shrtener.Worker, [arg1]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Shrtener.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/shrtener/repo.ex
defmodule Shrtener.Repo do
  use Ecto.Repo, otp_app: :shrtener

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

lib/shrtener/shortener/shortener.ex
defmodule Shrtener.Shortener do
  @moduledoc """
  The Shortener context.
  """

  import Ecto.Query, warn: false
  alias Shrtener.Repo
  alias Shrtener.Shortener.Url
  alias Ecto.Changeset

  @hashid Hashids.new([min_len: 3, salt: System.get_env("SECRET_KEY_BASE") || ""])

  @doc """
  Gets a single url.

  Raises `Ecto.NoResultsError` if the Url does not exist.

  ## Examples

      iex> get_url!(123)
      %Url{}

      iex> get_url!(456)
      ** (Ecto.NoResultsError)

  """
  def get_url!(id), do: Repo.get!(Url, id)
  def get_url_by_shortcode!(shortcode), do: Repo.get_by!(Url, shortcode: shortcode)

  @doc """
  Creates a url.

  ## Examples

      iex> create_url(%{field: value})
      {:ok, %Url{}}

      iex> create_url(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_url(attrs \\ %{}) do
    %Url{}
    |> Url.changeset(attrs)
    |> Repo.insert()
    |> generate_shortcode
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking url changes.

  ## Examples

      iex> change_url(url)
      %Ecto.Changeset{source: %Url{}}

  """
  def change_url(%Url{} = url) do
    Url.changeset(url, %{})
  end

  def increment_visits(%Url{} = url) do
    url
    |> Changeset.change(visits: url.visits + 1)
    |> Repo.update
  end

  defp generate_shortcode({:error, %Changeset{} = url}), do: {:error, url}
  defp generate_shortcode({:ok, %Url{} = url}) do
    url
    |> Changeset.change(shortcode: generate_random_shortcode(url.id))
    |> Repo.update
  end

  defp generate_random_shortcode(id) do
    Hashids.encode(@hashid, id)
  end
end

lib/shrtener/shortener/url.ex
defmodule Shrtener.Shortener.Url do
  use Ecto.Schema
  import Ecto.Changeset
  alias Shrtener.Shortener.Url

  @required ~w(url)a
  @optional ~w()a

  schema "urls" do
    field :shortcode, :string
    field :url, :string
    field :visits, :integer

    timestamps()
  end

  @doc false
  def changeset(%Url{} = url, attrs) do
    url
    |> cast(attrs, @required ++ @optional)
    |> validate_required(@required)
    |> validate_url(:url, message: "is not a valid URL")
    |> unique_constraint(:shortcode)
  end

  defp validate_url(changeset, field, options \\ []) do
    validate_change changeset, field, fn _, url ->
      case url |> String.to_charlist |> :http_uri.parse do
        {:ok, _} -> []
        {:error, msg} -> [{field, options[:message] || "invalid url: #{inspect msg}"}]
      end
    end
  end
end

lib/shrtener_web/controllers/url_controller.ex
defmodule ShrtenerWeb.UrlController do
  use ShrtenerWeb, :controller

  alias Shrtener.Shortener
  alias Shrtener.Shortener.Url

  def new(conn, _params) do
    changeset = Shortener.change_url(%Url{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"url" => url_params}) do
    case Shortener.create_url(url_params) do
      {:ok, url} ->
        changeset = Shortener.change_url(%Url{})
        render(conn, "new.html", changeset: changeset, url: url)
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def redirect_shortcode(conn, %{"shortcode" => shortcode}) do
    url = Shortener.get_url_by_shortcode!(shortcode)

    case Shortener.increment_visits(url) do
      {:ok, url} ->
        redirect(conn, external: url.url)
      {:error, %Ecto.Changeset{} = _changeset} ->
        redirect(conn, to: url_path(conn, :new))
    end

  rescue
    Ecto.NoResultsError -> redirect(conn, to: url_path(conn, :new))
  end
end

lib/shrtener_web/views/error_view.ex
defmodule ShrtenerWeb.ErrorView do
  use ShrtenerWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

lib/shrtener_web/views/layout_view.ex
defmodule ShrtenerWeb.LayoutView do
  use ShrtenerWeb, :view
end

lib/shrtener_web/views/page_view.ex
defmodule ShrtenerWeb.PageView do
  use ShrtenerWeb, :view
end

lib/shrtener_web/views/shared_view.ex
defmodule ShrtenerWeb.SharedView do
  use ShrtenerWeb, :view
end

lib/shrtener_web/views/url_view.ex
defmodule ShrtenerWeb.UrlView do
  use ShrtenerWeb, :view
end

lib/shrtener_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Thiago Belem">

    <title>Shrtener</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <%= render ShrtenerWeb.SharedView, "google_analytics.html", assigns %>
  </head>

  <body>
    <section class="hero is-primary has-text-centered">
      <div class="hero-body">
        <div class="container">
          <h1 class="title"><%= link("Shrtener", to: "/") %></h1>
          <p class="subtitle">A <b>simple</b> URL shortener!</p>
        </div>
      </div>
    </section>

    <section class="section has-text-centered">
      <%= render ShrtenerWeb.SharedView, "flash_messages.html", assigns %>

      <%= render @view_module, @view_template, assigns %>
    </section>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/shrtener_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

lib/shrtener_web/templates/shared/flash_messages.html.eex
<%= if get_flash(@conn, :info) do %>
  <div class="notification is-info" role="alert">
    <button class="delete"></button>
    <%= get_flash(@conn, :info) %>
  </div>
<% end %>

<%= if get_flash(@conn, :error) do %>
  <div class="notification is-danger" role="alert">
    <button class="delete"></button>
    <%= get_flash(@conn, :error) %>
  </div>
<% end %>

lib/shrtener_web/templates/shared/google_analytics.html.eex
<%= if System.get_env("GOOGLE_ANALYTICS_TRACKING_ID") do %>
  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=<%= System.get_env("GOOGLE_ANALYTICS_TRACKING_ID") %>"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', '<%= System.get_env("GOOGLE_ANALYTICS_TRACKING_ID") %>');
  </script>
<% end %>

lib/shrtener_web/templates/url/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="field has-addons">
    <div class="control is-expanded">
      <%= text_input f, :url, class: "input is-medium", placeholder: "Paste a link to compress" %>
      <%= error_tag f, :url %>
    </div>
    <div class="control">
      <%= submit raw('Shrten <i class="fa fa-compress"></i>'), class: "button is-info is-medium" %>
    </div>
  </div>
<% end %>

lib/shrtener_web/templates/url/new.html.eex
<div class="container">
  <div class="columns is-centered">
    <div class="column is-half is-narrow">
      <%= render "form.html", Map.put(assigns, :action, url_path(@conn, :create)) %>

      <%= if assigns[:url] do %>
        <hr />

        <div class="tile is-child notification is-info">
          <div class="content">
            <p>Here is your new URL:</p>
            <div class="field" style="width: 100%">
              <div class="control has-icons-left is-expanded">
                <input class="input is-medium" readonly value="<%= url_url(@conn, :redirect_shortcode, @url.shortcode) %>" onclick="this.setSelectionRange(0, this.value.length)" />
                <span class="icon is-small is-left">
                  <i class="fa fa-globe"></i>
                </span>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>